default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres
  host: <%= ENV['LOCAL'] == 'docker' ? 'db' : 'localhost' %>
  port: 5432

development:
  <<: *default
  database: digital_library_development

test:
  <<: *default
  database: digital_library_test

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  database: <%= ENV['DATABASE_URL'] %>
  # username: quxfagswpbcjor
  host: ec2-54-147-33-38.compute-1.amazonaws.com
  # password: 8d24c286c493b449215e7c07235ecbf3a53909f7fdb8a2187675907bbf3066e0
  port: 5432
